In [12]:
import pandas as pd
import numpy as np

In [6]:
s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
s.shape

(4,)

In [7]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
data={
    "name":["ali","sara","john"],
    "age":[20,21,22],
    "mark":[85,90,95]
}
data

{'name': ['ali', 'sara', 'john'], 'age': [20, 21, 22], 'mark': [85, 90, 95]}

In [10]:
df=pd.DataFrame(data)
df

name  age  mark
0   ali   20    85
1  sara   21    90
2  john   22    95

In [11]:
print("Columns:", df.columns)

Columns: Index(['name', 'age', 'mark'], dtype='object')


In [14]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
s1=pd.Series(a)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [18]:
data = {'a': 1, 'b': 2, 'c': 3}
s3 = pd.Series(data)
print(s3)


a    1
b    2
c    3
dtype: int64


In [19]:
data = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [23, 25, 22]
}
df = pd.DataFrame(data)
print(df)


   Name  Age
0   Ali   23
1  Sara   25
2  John   22


In [20]:
data = [
    {"Name": "Ali", "Age": 23},
    {"Name": "Sara", "Age": 25},
    {"Name": "John", "Age": 22}
]
df2 = pd.DataFrame(data)
print(df2)


   Name  Age
0   Ali   23
1  Sara   25
2  John   22


In [24]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
df3 = pd.DataFrame(arr, columns=['A','B','C'])
print(df3)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [25]:
df.describe()

Age
count   3.000000
mean   23.333333
std     1.527525
min    22.000000
25%    22.500000
50%    23.000000
75%    24.000000
max    25.000000

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


In [66]:
s=pd.Series([10,20,30,40,'a'])


In [67]:
a.values

array([10, 20, 30, 40, 'a'], dtype=object)

In [68]:
a.index


RangeIndex(start=0, stop=5, step=1)

In [69]:
s.name

In [70]:
s.name="numbers"


In [71]:
s

0    10
1    20
2    30
3    40
4     a
Name: numbers, dtype: object

In [72]:
#### indexing

In [73]:
s[0]

10

In [74]:
s[0:2]

0    10
1    20
Name: numbers, dtype: object

In [75]:
## i-> location based indexing

In [76]:
s.iloc[3]

40

In [77]:
s[[0,1]]

0    10
1    20
Name: numbers, dtype: object

In [78]:
s.iloc[[0,1]]

0    10
1    20
Name: numbers, dtype: object

In [81]:
inde=["a","b","c","d","f"]

In [82]:
s.index=inde

In [83]:
s

a    10
b    20
c    30
d    40
f     a
Name: numbers, dtype: object

In [84]:
s["a"]

10

In [85]:
##loc -> label based indexing
# in label based indexing  your start as well as stop values bots are included in output
print(s.loc["a"])
s.loc["a":"d"]

10


a    10
b    20
c    30
d    40
Name: numbers, dtype: object

In [86]:
s.loc["a"]

10

In [88]:
s1={
    "apple":10,
    "banana":80,
    "avacado":70,
    "mango":50,
    "kiwi":60

}

In [94]:
s2=pd.Series(s1,name="protein")
df=s2.to_frame()
print(df)

         protein
apple         10
banana        80
avacado       70
mango         50
kiwi          60


In [95]:
s2.dtype

dtype('int64')

In [97]:
s1["kiwi"]

60

## tasks

### Create a Series from a Python list.

In [99]:
a=[10, 20, 30, 40,50 ]
s1=pd.Series(a)
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Create a DataFrame from a dictionary.


In [104]:
dic={
    "name":["luffy","zoro","sanji"],
    "age":[19,22,21],
    "position":["captain","swords man","cook"]
}

In [105]:
dic

{'name': ['luffy', 'zoro', 'sanji'],
 'age': [19, 22, 21],
 'position': ['captain', 'swords man', 'cook']}

In [106]:
s2=pd.DataFrame(dic)
s2

name  age    position
0  luffy   19     captain
1   zoro   22  swords man
2  sanji   21        cook

In [107]:
s2.shape

(3, 3)

In [108]:
s2.columns

Index(['name', 'age', 'position'], dtype='object')

### Create a Series of numbers 1–10.

In [111]:
s=pd.Series(range(1,11))
ind=["a","b","c","d","f","g","h","i","j","k"]
s.index=ind
s

a     1
b     2
c     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
dtype: int64

### Create a DataFrame with two columns: Name, Age.

In [112]:
di={
    "name":["tanjiro","zenitsu","inuske"],
    "age":[17,18,16]
}
s1=pd.DataFrame(di)
s1

name  age
0  tanjiro   17
1  zenitsu   18
2   inuske   16

### Convert a NumPy array into a DataFrame.

In [113]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
s=pd.DataFrame(a)
s

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### Rename the columns of a DataFrame.

In [125]:
df=pd.DataFrame({
    "name":["ali","sara","john"],
    "age":[23,24,21]
})
print(f"orginal df : \n{df}")
df.columns=["full name","years"]
df

orginal df : 
   name  age
0   ali   23
1  sara   24
2  john   21


full name  years
0       ali     23
1      sara     24
2      john     21

### Add a new column to a DataFrame that calculates the square of another column.

In [128]:
df=pd.DataFrame({
    "name":["ali","sara","john"],
    "age":[23,24,21]
})
print(f"orginal df : \n{df}")

df["no of days lived"]=df["age"]*365
df["square"]=df["age"]**2
print(f" : \n{df}")

orginal df : 
   name  age
0   ali   23
1  sara   24
2  john   21
 : 
   name  age  no of days lived  square
0   ali   23              8395     529
1  sara   24              8760     576
2  john   21              7665     441


## extra questions

### Create a Series of the first 15 even numbers.

In [130]:
a=pd.Series(range(0,30,2))
a

0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18
10    20
11    22
12    24
13    26
14    28
dtype: int64

### Convert a NumPy array of 5 random integers into a Series.

In [176]:
a=np.random.randint(1,100,5)
print(a)
s1=pd.Series(a,name="random no")
s2=s1.to_frame()
print(s2)


[ 2 83 29 19 12]
   random no
0          2
1         83
2         29
3         19
4         12


### Create a DataFrame with columns: Student, Marks, Grade for 5 students.

In [140]:
clas={
    "name":["dustin","eleven","will","max","erica"],
    "mark":[80,75,88,90,99],
    "grade":["A","B","A","A+","O"]
}
df=pd.DataFrame(clas)
print(df)

     name  mark grade
0  dustin    80     A
1  eleven    75     B
2    will    88     A
3     max    90    A+
4   erica    99     O


### Add a new column “DoubleMarks” which is double the “Marks” column.

In [141]:
clas={
    "name":["dustin","eleven","will","max","erica"],
    "marks":[80,75,88,90,99],
    "grade":["A","B","A","A+","O"]
}
df=pd.DataFrame(clas)
print(df)
df["double marks"]=df["marks"]*2
df

     name  marks grade
0  dustin     80     A
1  eleven     75     B
2    will     88     A
3     max     90    A+
4   erica     99     O


name  marks grade  double marks
0  dustin     80     A           160
1  eleven     75     B           150
2    will     88     A           176
3     max     90    A+           180
4   erica     99     O           198

### Convert a 2×3 NumPy array into a DataFrame with column names X, Y, Z.

In [145]:
a=np.random.randint(1,20,size=(2,3))
print(a)
s1=pd.DataFrame(a)
s1.columns=["x","y","z"]
s1

[[12 16  7]
 [ 5  9  6]]


x   y  z
0  12  16  7
1   5   9  6

### Create a new column “Pass/Fail” based on Marks (>= 50 → Pass, else Fail).

In [180]:
clas={
    "name":["dustin","eleven","will","max","erica"],
    "marks":[80,75,88,90,99],
    "grade":["A","B","A","A+","O"]
}
df=pd.DataFrame(clas)
print(df)



df["marks"]
df["pass / fail "]= np.where(df["marks"]<85,'fail',"pass")
df
top=df[df["marks"]>80]


     name  marks grade
0  dustin     80     A
1  eleven     75     B
2    will     88     A
3     max     90    A+
4   erica     99     O


In [181]:
top

name  marks grade pass / fail 
2   will     88     A         pass
3    max     90    A+         pass
4  erica     99     O         pass

### Access the third and fifth elements from a Series.

In [155]:
a=pd.Series(range(1,10))
print(a)
a[[2,4]]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


2    3
4    5
dtype: int64

In [177]:
import pandas as pd

# Example DataFrame
data = {"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
        "Age": [25, 30, 22, 28, 24]}
print(df)
print()

df = pd.DataFrame(data)


# Access the first 3 rows
first_three_rows = df.head(3)
first_three_rows


   name  age
0   ali   23
1  sara   24
2  john   21



Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22

In [167]:
df=pd.DataFrame({
    "name":["ali","sara","john"],
    "age":[23,24,21]
})

df[["age"]]

age
0   23
1   24
2   21

In [182]:
import pandas as pd
import numpy as np

clas = {
    "name": ["dustin", "eleven", "will", "max", "erica"],
    "marks": [80, 75, 88, 90, 99],
    "grade": ["A", "B", "A", "A+", "O"]
}

df = pd.DataFrame(clas)
df["pass / fail"] = np.where(df["marks"] < 85, 'fail', "pass")

# Filter based on condition
top = df[df["marks"] > 80]

# Get only the names
topper_names = top["name"].tolist()
print(topper_names)


['will', 'max', 'erica']


In [183]:
top

name  marks grade pass / fail
2   will     88     A        pass
3    max     90    A+        pass
4  erica     99     O        pass

In [186]:
import pandas as pd
import numpy as np

clas = {
    "name": ["dustin", "eleven", "will", "max", "erica"],
    "marks": [80, 75, 88, 90, 99],
    "grade": ["A", "B", "A", "A+", "O"]
}

df = pd.DataFrame(clas)
df["pass / fail"] = np.where(df["marks"] < 85, 'fail', "pass")

# Filter based on condition
top = df[df["marks"] > 80]

# Get only the names
topper_names = top["name"]
print(topper_names)

2     will
3      max
4    erica
Name: name, dtype: object


In [187]:
top

name  marks grade pass / fail
2   will     88     A        pass
3    max     90    A+        pass
4  erica     99     O        pass

In [193]:
topper_age= top["marks"]
topper_age.to_frame()

marks
2     88
3     90
4     99

In [1]:
import pandas as pd
import numpy as np

clas = {
    "name": ["dustin", "eleven", "will", "max", "erica"],
    "marks": [80, 75, 88, 90, 99],
    "grade": ["A", "B", "A", "A+", "O"]
}

df = pd.DataFrame(clas)
df["pass / fail"] = np.where(df["marks"] < 85, "fail", "pass")

# Find topper (highest marks)
topper = df.loc[df["marks"].idxmax()]

print("Topper Name:", topper["name"])
print("Topper Marks:", topper["marks"])


Topper Name: erica
Topper Marks: 99
